# Generated by Django 3.2.15 on 2022-08-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nombre',
            name='description',
            field=models.TextField(),
        ),
    ]
