# Generated by Django 3.2.15 on 2022-08-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_nombre_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.TextField()),
                ('clave', models.TextField()),
                ('origen', models.IntegerField(choices=[('Comprobantes emitidos por el contribuyente', 'Comprobantes emitidos por el contribuyente'), ('Comprobantes recibidos por el contribuyente', 'Comprobantes recibidos por el contribuyente')], default=2)),
                ('tipo', models.IntegerField(choices=[(1, 'Factura'), (2, 'Liquidación de compra de bienes y prestación de servicios'), (3, 'Notas de Crédito'), (4, 'Notas de Débito'), (5, 'Guías de Remisión'), (6, 'Comprobante de Retención')], default=6)),
                ('establecimiento', models.IntegerField(choices=[(1, 'Todos'), (2, '001'), (3, '002'), (4, '003')], default=1)),
                ('dia', models.IntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31')])),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('anio', models.IntegerField(choices=[(1, '2022'), (2, '2021'), (3, '2020'), (4, '2019'), (5, '2018'), (6, '2017'), (7, '2016'), (8, '2015')])),
            ],
        ),
    ]
